### PR TITLE
Docker

### PR DESCRIPTION
**Pull request by zhujun98**
Add Dockerfile 
Add tests with docker-compose 
Add test with docker in Travis CI 
Move external header files into a new directory ${HOME}/share/, which is the location where the environment is set up.

### CODE REVIEW

**Comment by zhujun98** [comment]
Modify according to Hans' propose.

Fix the integration test due to recent change in karabo-bridge-py.

**Comment by tmichela** [comment]
sorry for the key change, but this reflects the latest state of key names received from the calibration pipeline. Maybe we should discuss with Steffen in order to keep the interface stable. I am personally keen to keep same key name as they appear in hdf files.

**Comment by zhujun98** [comment]
Don't worry! I agree it is important to keep the same key names as what shows in the hdf file.

**Comment by fangohr** [comment]
LGTM, thank you!

**Pull request merged**
