### PR TITLE
New autogen

### PR DESCRIPTION
**Pull request by zhujun98**
Further restructure the project and made a new script to ease build, install and test

```sh
show_usage()
{
    echo -e "\nUsage ./autogen.sh option [destination]"
    echo -e "\nValid options are:"
    echo -e " - download: download the dependencies;"
    echo -e " - build: build the library;"
    echo -e " - test: build and run unit test;"
    echo -e " - integration_test: build and run integration test (only client);"
    echo -e " - install: build and install to the destination folder, default to "${HOME}/share";"
    echo -e " - clean: remove the build directory and downloaded dependencies.\n"
}
```
Only coding style was modified in the main code (the struct visitor is also hidden from the user). 

Please review! Thank you! After this merge, I will tag it as 0.2.0? (to be consistent with the Python one)

### CODE REVIEW

**Comment by takluyver** [comment]
The doc changes look OK. I'm not really qualified to assess the C++ and build changes.

I'm a bit concerned that this is heading in the direction of maintaining our own mini build system, but I don't really know of any alternatives that would be better for downloading and building dependencies as part of the build.

I don't think there's any need to keep the version numbers in step between the Python and C++ clients.

**Comment by zhujun98** [comment]
In principle, we can include the header files from cppzmq and msgpack in our project. But Hans does not like the idea.

Another option would be add submodules. Then the user will always clone the master repo of the dependencies. (I have not used any advanced options of submodules , so I have no ideal whether it is possible to choose tag)

The most tricky part is the zeromq (in c) library. It is required to be installed. In our clusters, the user needs to appoint the location since it is not allowed to be installed in the system folders like '/usr/local/lib'. And we need to link it when building. Also, since it is not in the system folder, the normal cmake way of find package does not work.

For experienced users like Lutz, they do not need any instructions as long as they know which libraries are required. However, I have been asked several time by other people who have trouble in building their projects with the cpp client: whether it is a header only libraries or a library that people can install and only link to it.  Unfortunately, neither is the case.

The bash script is simply a convenient tool. It automatically download and put all header files and libraries in a folder, and the user can have all the header files and libraries in 4 lines of CMakeLists as I showed in the example
```
set(INSTALL_PATH "$ENV{HOME}/share")
set(zmq_LIBRARY "${INSTALL_PATH}/zeromq/lib/libzmq.so")
include_directories(${INSTALL_PATH}/zeromq/include)
include_directories(${INSTALL_PATH}/include)
```
Moreover, it is tedious to download the three dependencies separately and install them. 

In a word, the user can feel free to do whatever they like as I have specified the versions of dependencies. If they do not know how to do it or are too lazy, they can simply user the bash script. The build system is still cmake and make, the script is only used to modify the cmake options.

**Comment by tmichela** [comment]
Working great for me on maxwell, LGTM!

**Comment by zhujun98** [comment]
Thanks for the review! I will merge.

**Pull request merged**
